weights: yolov5s.pt
cfg: ./models/yolov5s.yaml
data: ./data/speed_mp.yml
hyp: data/hyp.finetune.yaml
epochs: 100
batch_size: 48
img_size:
- 416
- 416
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
name: ''
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: runs/
workers: 8
total_batch_size: 48
world_size: 1
global_rank: -1
